# Generated by Django 5.0.2 on 2024-04-17 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=100)),
                ('game_started', models.DateTimeField(auto_now_add=True)),
                ('pieces_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OpponentMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves_list', models.TextField()),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_moves', to='tictacky.gamestate')),
            ],
        ),
        migrations.CreateModel(
            name='WinOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_combination', models.TextField()),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_outcomes', to='tictacky.gamestate')),
            ],
        ),
    ]
