# Generated by Django 5.0.2 on 2024-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictacky', '0002_gamestate_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='pieces_available',
            field=models.TextField(default='[]'),
        ),
    ]
