# Generated by Django 5.0.2 on 2024-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictacky', '0003_alter_gamestate_pieces_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='pieces_available',
            field=models.TextField(default='["A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3"]'),
        ),
    ]
