# Generated by Django 5.0.2 on 2024-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictacky', '0005_winoutcome_my_strategy_winoutcome_opponent_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opponentmoves',
            name='moves_list',
            field=models.JSONField(default=list),
        ),
    ]
