# Generated by Django 5.0.2 on 2024-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictacky', '0006_alter_opponentmoves_moves_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opponentmoves',
            name='game_state',
        ),
        migrations.AddField(
            model_name='opponentmoves',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
